/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as AuthLayoutRouteImport } from "./pages/_auth/layout";
import { Route as AppLayoutRouteImport } from "./pages/_app/layout";
import { Route as AppIndexRouteImport } from "./pages/_app/index";
import { Route as AuthSignInIndexRouteImport } from "./pages/_auth/sign-in/index";

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppLayoutRoute,
} as any);
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: "/sign-in/",
  path: "/sign-in/",
  getParentRoute: () => AuthLayoutRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute;
  "/sign-in": typeof AuthSignInIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof AppIndexRoute;
  "/sign-in": typeof AuthSignInIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppLayoutRouteWithChildren;
  "/_auth": typeof AuthLayoutRouteWithChildren;
  "/_app/": typeof AppIndexRoute;
  "/_auth/sign-in/": typeof AuthSignInIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/sign-in";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/sign-in";
  id: "__root__" | "/_app" | "/_auth" | "/_app/" | "/_auth/sign-in/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren;
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppLayoutRoute;
    };
    "/_auth/sign-in/": {
      id: "/_auth/sign-in/";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof AuthSignInIndexRouteImport;
      parentRoute: typeof AuthLayoutRoute;
    };
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute;
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
};

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
);

interface AuthLayoutRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute;
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
};

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
