name: Run Renovate Automerge

on: [pull_request, merge_group]

jobs:
  run-renovate-automerge:
    name: Run Renovate Automerge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.1

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run main tasks
        run: |
          pnpm typecheck
          pnpm lint
