name: Tests

on:
  workflow_run:
    workflows: ["Code check"]
    types: [completed]

jobs:
  integration:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        project: [./templates/fastify, ./templates/nest]

    name: Integration test (${{ matrix.project }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: pnpm install

      - name: Run integration test
        working-directory: ${{ matrix.project }}
        run: pnpm test:integration

  e2e:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        project: [.]

    name: E2E test (${{ matrix.project }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: pnpm install

      - name: Run e2e test
        working-directory: ${{ matrix.project }}
        run: pnpm test:e2e
